language: node_js
node_js:
  - 10

addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_install:
  - npm install -g @lhci/cli@0.3.x
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo pg_ctlcluster 12 main restart

before_script:
  - source config/test.env
  - sudo -u postgres createdb ${PGDATABASE}
  - sudo -u postgres psql -c "CREATE ROLE ${PGUSER} WITH LOGIN PASSWORD '${PGPASSWORD}'"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${PGDATABASE} to ${PGUSER};"
  - yarn sequelize:test db:migrate
  - yarn sequelize:test db:seed:all
  - yarn workspace server db-import-tests:test -c ${IMPORT_ARIA_AT_TESTS_COMMIT_1}
  - yarn workspace server db-import-tests:test -c ${IMPORT_ARIA_AT_TESTS_COMMIT_2}

script:
  - yarn test
