---
- hosts: all
  become_method: sudo
  pre_tasks:
    - include: tasks/prompt-for-become-password.yml
      when: needs_become_password
  roles:
    - permissions
    - database
    - nodejs
    - proxy
    - role: certbot
      when: deployment_mode != 'development'
    - application
  handlers:
    - name: Reload systemd daemon
      become: yes
      systemd:
        daemon_reload: True
    - name: Restart journald daemon
      become: yes
      systemd:
        name: systemd-journald
        state: restarted
  vars_files:
    - vars/main.yml
