---
- name: Install version control software
  apt:
    name: git
    state: present

- name: Define source code location
  set_fact:
    source_dir: /home/{{application_user}}/aria-at-report

- name: Upload project source code
  synchronize:
    src: '{{playbook_dir}}/..'
    dest: '{{source_dir}}'
  when: deployment_mode != 'development'

- name: Link application code
  file:
    dest: '{{source_dir}}'
    src: /vagrant
    state: link
  when: deployment_mode == 'development'

- name: Install Node.js dependencies
  command: yarn install
  args:
    chdir: '{{source_dir}}'

- name: Insert environment configuration file
  copy:
    dest: /home/{{application_user}}/config.env
    src: files/config-{{deployment_mode}}.env
    owner: '{{application_user}}'
  register: environment_config

- name: Create database and database user
  command: sudo -u postgres ./db/scripts/db_init.sh {{environment_config.dest}}
  args:
    chdir: '{{source_dir}}'

- name: Migrate database
  command: ./db/scripts/db_migrate.sh {{environment_config.dest}}
  args:
    chdir: '{{source_dir}}'

- name: Import tests into database
  command: ./db/scripts/db_import_tests.sh {{environment_config.dest}}
  args:
    chdir: '{{source_dir}}'
