---
# Ansible's `vars_prompt` feature is the most direct way to collect input from
# the user running the provisioning script. However, that feature can only be
# used at the level of an Ansible Playbook. Because only some hosts require the
# use of `sudo`, `vars_prompt` isn't appropriate for this case.
- name: prompt for sudo password
  pause:
    prompt: Please enter the sudo password
    echo: no
  register: sudo_password_prompt
- name: set playbook_password fact
  set_fact:
    ansible_become_pass: "{{ sudo_password_prompt.user_input }}"
